---
version: "2.1"
services:
  teemip:
    image: lscr.io/linuxserver/nginx:latest
    container_name: teemip
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:letsencrypt-imagemagick|linuxserver/mods:universal-cron
    volumes:
      - ${LOCVOL1}teemip:/config
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped
    #depends_on:
    #- teemip-db
#
  teemip-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: teemip-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-cron
      #- MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      #- MYSQL_DATABASE=USER_DB_NAME #optional
      #- MYSQL_USER=MYSQL_USER #optional
      #- MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    volumes:
      - ${LOCVOL1}teemip-db:/config
    #ports:
    #  - 3306:3306
    restart: unless-stopped
#
  adminer:
    image: adminer:latest
    restart: unless-stopped
    #ports:
    #  - 8101:8080
#
#
#
networks:
  default:
    external: true
    name: ${CONNET}
